# Resultats

```{r setup, include = FALSE}
# Aquest bloc de codi s'executa primer però no es mostra al document final.
# S'encarrega de carregar totes les dades i preparar els objectes necessaris.

# 1. Carreguem funcions i paquets
source('R/00_setup.R')
source('data/01_data_golvin/00_dimensions_amfiteatres_golvin.R')
source('data/02_data_vazquez/00_dimensions_amfiteatres_vazquez.R')
source('R/02_tab_summary.R')


amphi_load_packages(
  update_packages = FALSE)

# 2. Creem les matrius de dades
df_golvin <- load_dimensions_golvin(
  filtrar_provincia = c('hispania', 'panonnia', 'britannia'),
  filtrar_pais = NULL,
  seleccionar_columnes = NULL,
  retornar_originals = FALSE)

df_vazquez <- load_dimensions_vazquez(
  filtrar_edifici = 'amphitheater',
  filtrar_pais = NULL,
  filtrar_provincia = c('hispania', 'panonnia', 'britannia'),
  seleccionar_columnes = NULL,
  retornar_originals = FALSE)

# 3. Generem les llistes de taules de resum
tab_01 <- tab_summary(
  df = df_golvin,
  grup_by = 'nom',
  stats_adicionals = FALSE,
  seleccio_variables = starts_with(c('amplada', 'alcada')),
  na.rm = TRUE,
  bind_rows = FALSE,
  digits = 1)

tab_02 <- tab_summary(
  df = df_vazquez,
  grup_by = 'nom',
  stats_adicionals = FALSE,
  seleccio_variables = starts_with(c('amplada', 'alcada')),
  na.rm = TRUE,
  bind_rows = FALSE,
  digits = 1)

```


## Resultats de Golvin (1988)

A continuació es mostren les estadístiques descriptives de les dimensions dels amfiteatres segons les dades de Golvin, agrupades per província romana. Cada pestanya correspon a una variable diferent.

```{r golvin-tables, panel = 'tabset'}

```


## Resultats de Vázquez (2023)

```{r vazquez-tables, panel="tabset"}


```
